//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DixiFormaConsoleClient.DixiFormaServer {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Message", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Message : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid MessageIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SendingTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DixiFormaConsoleClient.DixiFormaServer.User UserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid MessageId {
            get {
                return this.MessageIdField;
            }
            set {
                if ((this.MessageIdField.Equals(value) != true)) {
                    this.MessageIdField = value;
                    this.RaisePropertyChanged("MessageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SendingTime {
            get {
                return this.SendingTimeField;
            }
            set {
                if ((this.SendingTimeField.Equals(value) != true)) {
                    this.SendingTimeField = value;
                    this.RaisePropertyChanged("SendingTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DixiFormaConsoleClient.DixiFormaServer.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DixiFormaServer.IServiceDF", CallbackContract=typeof(DixiFormaConsoleClient.DixiFormaServer.IServiceDFCallback))]
    public interface IServiceDF {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDF/Connect", ReplyAction="http://tempuri.org/IServiceDF/ConnectResponse")]
        bool Connect(DixiFormaConsoleClient.DixiFormaServer.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDF/Connect", ReplyAction="http://tempuri.org/IServiceDF/ConnectResponse")]
        System.Threading.Tasks.Task<bool> ConnectAsync(DixiFormaConsoleClient.DixiFormaServer.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDF/Register", ReplyAction="http://tempuri.org/IServiceDF/RegisterResponse")]
        bool Register(DixiFormaConsoleClient.DixiFormaServer.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDF/Register", ReplyAction="http://tempuri.org/IServiceDF/RegisterResponse")]
        System.Threading.Tasks.Task<bool> RegisterAsync(DixiFormaConsoleClient.DixiFormaServer.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDF/Disconnect", ReplyAction="http://tempuri.org/IServiceDF/DisconnectResponse")]
        void Disconnect(DixiFormaConsoleClient.DixiFormaServer.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDF/Disconnect", ReplyAction="http://tempuri.org/IServiceDF/DisconnectResponse")]
        System.Threading.Tasks.Task DisconnectAsync(DixiFormaConsoleClient.DixiFormaServer.User user);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceDF/SendMsg")]
        void SendMsg(DixiFormaConsoleClient.DixiFormaServer.Message message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceDF/SendMsg")]
        System.Threading.Tasks.Task SendMsgAsync(DixiFormaConsoleClient.DixiFormaServer.Message message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceDFCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceDF/MsgCallback")]
        void MsgCallback(DixiFormaConsoleClient.DixiFormaServer.Message message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceDFChannel : DixiFormaConsoleClient.DixiFormaServer.IServiceDF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceDFClient : System.ServiceModel.DuplexClientBase<DixiFormaConsoleClient.DixiFormaServer.IServiceDF>, DixiFormaConsoleClient.DixiFormaServer.IServiceDF {
        
        public ServiceDFClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ServiceDFClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ServiceDFClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDFClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDFClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public bool Connect(DixiFormaConsoleClient.DixiFormaServer.User user) {
            return base.Channel.Connect(user);
        }
        
        public System.Threading.Tasks.Task<bool> ConnectAsync(DixiFormaConsoleClient.DixiFormaServer.User user) {
            return base.Channel.ConnectAsync(user);
        }
        
        public bool Register(DixiFormaConsoleClient.DixiFormaServer.User user) {
            return base.Channel.Register(user);
        }
        
        public System.Threading.Tasks.Task<bool> RegisterAsync(DixiFormaConsoleClient.DixiFormaServer.User user) {
            return base.Channel.RegisterAsync(user);
        }
        
        public void Disconnect(DixiFormaConsoleClient.DixiFormaServer.User user) {
            base.Channel.Disconnect(user);
        }
        
        public System.Threading.Tasks.Task DisconnectAsync(DixiFormaConsoleClient.DixiFormaServer.User user) {
            return base.Channel.DisconnectAsync(user);
        }
        
        public void SendMsg(DixiFormaConsoleClient.DixiFormaServer.Message message) {
            base.Channel.SendMsg(message);
        }
        
        public System.Threading.Tasks.Task SendMsgAsync(DixiFormaConsoleClient.DixiFormaServer.Message message) {
            return base.Channel.SendMsgAsync(message);
        }
    }
}
